CREATE TYPE "public"."source" AS ENUM('SAVED', 'PURCHASED', 'TRADED', 'GIFTED', 'OTHER');--> statement-breakpoint
CREATE TABLE "seeds" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "seeds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"species" varchar(255) NOT NULL,
	"source" "source" NOT NULL,
	"harvest_year" integer,
	"viability_years" integer,
	"quantity" integer NOT NULL,
	"photo_url" varchar(500),
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
